### ISSUE TITLE
Some thoughts on textures/artworks

### ISSUE THREAD

**Issue by Quantumzhao** [przemykomo/simple-planes#10]
Hello, I love your mod very much, especially its vanilla feeling. 
This is a gorgeous work overall, and I am interested in making some little contributions in improving the textures, specifically the item thumbnails. 
If you think there is a need to change some of the thumbnails, I would be delighted to be involved in your project.

**Comment by przemykomo** [comment]
Sure! You may change engine and upgrades textures.
