### ISSUE TITLE
Holding shift while in an inventory menu then exiting the inventory menu

### ISSUE THREAD

**Issue by EgaCool** [przemykomo/simple-planes#110]
If you hold shift while inside of the inventory menu then exit the inventory menu while still holding shift, it will kick you out of the plane. This is an issue because you could get kicked out of the plane accidentally while you are flying it and die and lose your stuff.

**Comment by przemykomo** [comment]
I think that's how it's supposed to work. When you hold shift you leave the boat too so I don't really understand what's the issue with planes.
