### ISSUE TITLE
[Question] Modify recipes of the plane workbench

### ISSUE THREAD

**Issue by Raft08** [przemykomo/simple-planes#112]
Hello i'm making a modpack,
And i want to change recipes of the plane workbench

How can i do this?

**Comment by przemykomo** [comment]
Use any datapack mod which can replace normal recipes. Then you can replace the aircraft recipes just like the normal ones.
https://github.com/przemykomo/simple-planes/blob/master/src/main/resources/data/simpleplanes/recipes/helicopter.json here is an example helicopter recipe

**Comment by Raft08** [comment]
Ok thanks!
