### ISSUE TITLE
Helicopter recipe bug

### ISSUE THREAD

**Issue by Raidobw2** [przemykomo/simple-planes#113]
Hello, there appears to be a bug with the Helicopter recipe in the plane workbench. Crafting a helicopter requires 2 propellers but will only consume one on craft.

Versions:
Minecraft `1.18.2`
Forge `40.1.52`
Simple Planes `simpleplanes-1.18.2-4.13.4.jar`
Modpack `FTB Plexiglass Mountain 1.1.1`

Screenshots:
What is in JEI
![image](https://user-images.githubusercontent.com/17010632/176799138-5db747fc-2849-4bef-afd8-b5cf0138f1ee.png)
Putting materials in
![image](https://user-images.githubusercontent.com/17010632/176799173-05cc79c4-8ccd-41fb-aa48-e5b96063593d.png)
Taking the Helicopter while crafting completes, one propeller remains
![image](https://user-images.githubusercontent.com/17010632/176799199-7fb0ea0a-f687-473e-ad26-b2a17e65c704.png)
Thanks in advance for checking it out!

**Comment by przemykomo** [comment]
Thanks for reporting!
