### ISSUE TITLE
conflict with large ore deposit won't let you join server

### ISSUE THREAD

**Issue by moidu21** [przemykomo/simple-planes#115]
hello

after installing it on my server i can't join the world 

there is no crash report client/server

if yo need more info tell me but it should be easy to reproduce just launch a server with plane mod and try to connect to it

thanks
minecraft forge : 41.0.63
minecraft 1.19
simple planes : 1.19 4.14.1

sceernshot of client error

http://quentfr21.free.fr/bug/bug.png

**Comment by przemykomo** [comment]
It seems to be a problem with a different mod. You have to check client/server logs.

**Comment by moidu21** [comment]
just if you want to know 

after some testing there is a conflict with large ore deposit 
https://www.curseforge.com/minecraft/mc-mods/large-ore-deposits

thanks for the help i report the problem to large ore deposit

you can close it if you want
