### ISSUE TITLE
Suggestion: Expose vehicles models to resource packs

### ISSUE THREAD

**Issue by JDLENL** [przemykomo/simple-planes#116]
Self-explanatory title. There is currently no way to change the model (or static parts of the texture like the propeller) of your vehicle entities with a resource pack.

**Comment by przemykomo** [comment]
It's not possible to do without changing like half of minecraft rendering code like optifine does. You can change the textures there https://github.com/przemykomo/simple-planes/tree/master/src/main/resources/assets/simpleplanes/textures/plane_upgrades
