### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by KostromDan** [przemykomo/simple-planes#123]
I was flying on a plane abount 15 minutes, then game crashed.
[crash-2022-07-29_21.07.35-server.txt](https://github.com/przemykomo/simple-planes/files/9222402/crash-2022-07-29_21.07.35-server.txt)

**Comment by KostromDan** [comment]
[latest.log](https://github.com/przemykomo/simple-planes/files/9222407/latest.log)

**Comment by przemykomo** [comment]
It is probably an issue with the framework mod, not simple planes.
