### ISSUE TITLE
odd tnt and seat placment 

### ISSUE THREAD

**Issue by DiggityMan420** [przemykomo/simple-planes#126]
i added a seat and bombing upgrade and i get this odd texture thru the window  see pic https://blockshot.ch/c58p that's tnt thru the side and seat thru the top

see gif https://blockshot.ch/OLG7

**Comment by DiggityMan420** [comment]
also would be cool to add liquid fuel engines like diesel or gasoline

**Comment by przemykomo** [comment]
It's a limitation of minecraft's rendering engine, so the only thing that can be done about it is removing the windows.
