### ISSUE TITLE
Suggestion: Add Roll

### ISSUE THREAD

**Issue by rockman422** [przemykomo/simple-planes#131]
I think it must be fun to add maneuver "Roll"(Fig.1) to stylish movement like immelmann turn or Split S.

I'm enjoying this mod, thank you. ; )

**Comment by rockman422** [comment]
![image](https://user-images.githubusercontent.com/111558509/185561038-25ce289a-268f-470e-9be7-5297950d0b50.png)
Fig.1

**Comment by rockman422** [comment]
Fig.1
![fig1](https://user-images.githubusercontent.com/111558509/185561470-43296a81-30da-40a3-9291-65790652c771.jpg)

**Comment by przemykomo** [comment]
Do you mean to change roll without changing yaw?

**Comment by rockman422** [comment]
No, I think yaw is incompatible with roll.
The idea is this:
・Removing yaw status
・Change yaw input(now assigned to "A" and "D"), into Roll input.
When a player want to turn right, he need push "D" for a bit to roll some degrees, and push "W" to pitch up.
I think body control becomes a bit harder, but the movements will be nice.

**Comment by najlitarvan** [comment]
i personally think roll would be nicer too, would allow for some more fun maneuvers, especially with the booster upgrade, it is a real pain rn if you go inverted rn, but having roll control would only mean you have to do a roll

**Comment by przemykomo** [comment]
It's done in version 5.0.0.
