### ISSUE TITLE
Adding armor to a helicopter causes characters not to show up

### ISSUE THREAD

**Issue by nitbe** [przemykomo/simple-planes#132]
Adding armor to a helicopter causes characters [https://media.discordapp.net/attachments/754733252786520166/1010050414533689374/2022-08-19_12.56.03.png?width=1124&height=586](url)
[https://media.discordapp.net/attachments/754733252786520166/1010050414906986536/2022-08-19_12.56.11.png?width=1124&height=586](url)

**Comment by przemykomo** [comment]
The only way to fix this issue is to remove windows from the armor, and I'm not sure whether I want to do that.
