### ISSUE TITLE
Helicopters won't start!

### ISSUE THREAD

**Issue by Venoxy2310** [przemykomo/simple-planes#134]
Helicopters don't start on multiplayer servers when in survival mode Coal and everything was done right!

**Comment by shadow7412** [comment]
They work for me (though I'm using the electric engine). You need to give details, and version numbers for this to be a useful bug report.

> and everything was done right!

Perhaps mention the exact steps you did to create the helicopter. 99% of the time, people who say this are wrong...

**Comment by TheLynx927** [comment]
Hello, Though poorly worded I have the same issue with Coal engines. No matter how you try to add fuel the plane or helicopter do not fly despite showing plane is burning fuel. I have had this issue on both 1.19 and 1.19.2 with whatever the forge recommended version was for both. I am running other mods but with two reports I don't think it is a conflict.

**Comment by przemykomo** [comment]
Okay so my theory is that you don't understand that you have to use space to go up. Check keybindings.

**Comment by TheLynx927** [comment]
Wow what a genius my problem is solved! On a serious note, confirmed key bindings and everything works normally with the electric engines.

**Comment by TheLynx927** [comment]
FYI at least my version of the issue was resolved with the latest update. Cheers
