### ISSUE TITLE
crash using cgm ammo

### ISSUE THREAD

**Issue by greywolfish** [przemykomo/simple-planes#139]
strangely works fine on modded single player. but when playing on a server there is an instant client side crash when trying to use cgm ammo. This popped up on console, not sure if its helpful!      UUID of added entity already exists: FallingBlockEntity['Falling Block'/9114, l='ServerLevel[The Outcasts - Metropolis 2]', x=678.50, y=81.00, z=-90.50]

**Comment by przemykomo** [comment]
Are you able to show the entire log?

**Comment by greywolfish** [comment]
sure thing!
[Crash Report.pdf](https://github.com/przemykomo/simple-planes/files/9690785/Crash.Report.pdf)

**Comment by Niwood01** [comment]
I have the same issue, with the last version of the mod and the same error in my logs
