### ISSUE TITLE
Doesn't work in version 1.19.2

### ISSUE THREAD

**Issue by anewri32** [przemykomo/simple-planes#154]
The motors that move the planes and the helicopter seem non-functional, I tried to give them fuel and they didn't consume it, I couldn't raise the helicopter or the plane either, I thought it was due to a conflict with the keys but I changed them and the problem persisted. The power-operated motor was also unable to move the helicopter.

**Comment by przemykomo** [comment]
... checked keys and didn't see the throttle ones? Use arrow keys to turn it on.
