### ISSUE TITLE
[BUG] [1.18.2 FORGE] Planes don't work at all

### ISSUE THREAD

**Issue by Camawama** [przemykomo/simple-planes#155]
I'm working on my modpack (CamaCraft) and while updating some mods, it appears the planes just stopped working entirely.

https://user-images.githubusercontent.com/43620900/218172259-5bb7a054-4597-409d-a316-0eda7a73a776.mp4

**Comment by przemykomo** [comment]
Use arrow keys to change throttle...

**Comment by Camawama** [comment]
holy shit, this is the best update the mod has had!

**Comment by Camawama** [comment]
We need the ability to rebind the fire button.
