### ISSUE TITLE
Unable to stay in plane or helicopter.

### ISSUE THREAD

**Issue by Thunt0719** [przemykomo/simple-planes#172]
I am not sure why, but I am unable to stay in the plane, or helicopter. I can craft, add to, and place the craft, just can't stay mounted. All the other mods work fine, no issues loading. 

https://github.com/przemykomo/simple-planes/assets/139728206/1b310a66-22dc-47df-93a8-aa0e0b86499e

![Screenshot (75)](https://github.com/przemykomo/simple-planes/assets/139728206/c4445fa3-9199-4dcb-9281-2cfea62f13b3)
![Screenshot (74)](https://github.com/przemykomo/simple-planes/assets/139728206/ee676ebb-5181-4079-abdf-3665996ec43f)
![Screenshot (72)](https://github.com/przemykomo/simple-planes/assets/139728206/dfab6af0-8945-488e-91b4-a968d9c30b2a)

**Comment by DragonEater2008** [comment]
Downgrade your forge version to 47.1.0 if that is an option, I don’t know why that works, but it works

**Comment by Thunt0719** [comment]
> Downgrade your forge version to 47.1.0 if that is an option, I don’t know why that works, but it works

Works fine now, Thank you.
