### ISSUE TITLE
Falling Through Plane When Boarding

### ISSUE THREAD

**Issue by SquigMo** [przemykomo/simple-planes#174]
I'm using the 1.20.1 Forge version and whenever I right click on my helicopter to get inside it, I'm moved inside the helicopter but immediately "fall through". I'm not pushing left shift but it's like I'm not actually in the plane at all. I checked the key binds and it doesn't look like anything funky there. Any ideas on how to resolve this?

**Comment by DragonEater2008** [comment]
Which forge version are you using?

which simple planes version are you using?
