### ISSUE TITLE
Suggestion - change the fuel warning?

### ISSUE THREAD

**Issue by Tokeli** [przemykomo/simple-planes#18]
In the 1.15 version at least, smoke comes from the furnace at all times, so it's almost entirely impossible to tell when the propeller starts smoking if you're flying in a straight line as they just blend together entirely, or can't be seen at all in 1st person. I'm mostly forced to just keep spamming right-click constantly to ensure it doesn't suddenly plummet out of the sky.

Maybe have the smoke from the furnace be white by default, and it turns black when you're low on fuel- or a sound plays.

**Comment by adoxentor** [comment]
added fuel bar to the gui
