### ISSUE TITLE
Plane can't turn anymore.

### ISSUE THREAD

**Issue by The-Artificer** [przemykomo/simple-planes#182]
1.19 controls don't work like they did before. Pressing A or D just causes the plane to spin. In order to turn the plane, you have to constantly turn it to the side and then fight to pull it up again. It's not fun or intuitive to control. The actual rotation of the plane feels way too sensitive for far too little change in direction. Multiple players complained about lack of camera-locking and induced motion-sickness.

**Comment by przemykomo** [comment]
That's how it's intended. You can use left/right arrows to rotate them left or right.
