### ISSUE TITLE
[Suggestion] Backport

### ISSUE THREAD

**Issue by andryqx** [przemykomo/simple-planes#195]
Hello! Is it possible to make backport to 1.16.5? 1.18.2+ versions are too unoptimized cuz of new generation. I'm making my server (1500+ members on discord), and this mod is really must have... i'd help you with bugreports or testing backport, if you would make it. On 1.16.5 there aren't playable alternatives with guns. CGM is available for 1.16.5, so, i think that it's possible to make port. (sorry for my english)

**Comment by przemykomo** [comment]
It's not possible considering I just work on the mod in my free time.
