### ISSUE TITLE
Compatibility Suggestion: Take no damage from Vic's Point Blank bullets

### ISSUE THREAD

**Issue by GeorgeBaker1** [przemykomo/simple-planes#198]
Just as in the title, is there a way to have Vic's point blank's guns deal no damage? The planes/helicopters immediately despawn when shot with any VPB gun.

VPB's rocket launchers etc. work perfectly fine, but the guns just break the planes/helicopters into an item.

**Comment by GeorgeBaker1** [comment]
Ah shoot... It appears they take damage normally in survival. Still way too much, is there a way to add resistance to certain damages? Or would I have to make a fork for that?

Sorry for wasting time, thanks for the quick reply!

**Comment by przemykomo** [comment]
It should take as much damage as any other entity, you can add armor to have resistance to all types of damage.
