### ISSUE TITLE
[Forge 1.19.2] Crash on use with CGM ammo

### ISSUE THREAD

**Issue by dagobertdu94** [przemykomo/simple-planes#202]
The game crashes if I try to use CGM ammo in helicopters.
Crashreport: https://pastebin.com/CMNxB5dG

I use v5.2.2 of Simple Planes and v1.3.7 of CGM, both for Forge 1.19.2.
I have the Forge version 43.3.0 if that may be important to solve that problem.

It would be nice if anyone could tell me if it's a real bug or a mistake on my side...

**Comment by TheDoopers** [comment]
Its been a reported issue since January, seems to be 1.19.2 exclusive and completely ignored by the developers. The crash is not your fault.
