### ISSUE TITLE
Plane landing server crash

### ISSUE THREAD

**Issue by CrypticSiri** [przemykomo/simple-planes#21]
Hi, I'm running a 1.15.2-forge-31.2.44 server with Simple Planes 3.0.0.2, and whenever a player lands a plane, the server crashes. It doesn't seem to occur when the player lands on smooth, empty ground, but instead when they land on something like a tree.
Crash log / mod list: https://pastebin.com/JD9WgxSD
The full server log was too large for pastebin, so if you need me to find another way to include it, let me know.

**Comment by adoxentor** [comment]
try the new version pls (3.0.1.0)

**Comment by CrypticSiri** [comment]
The problem appears to be fixed. Thank you!
