### ISSUE TITLE
[Suggestions] Some suggestions to improve the experience

### ISSUE THREAD

**Issue by Zahkriiven** [przemykomo/simple-planes#34]
Hello, i have some suggestions that i think could improve the experience of playing with the mod.
But first thank you for the work and dedication.

1. Speed control. I feel like is not that easy to land when using the small plane or the dragon head upgrade. Some way of slowing down the plane like when it is out of fuel makes it a lot easier.
2. More inventory space for the cargo plane. I think the cargo plane concept is pretty cool but a double chest size when all 6 chest upgrades are applied feels small. Maybe put it as a config?. As a bonus to this, load and unload cargo from planes automatically like using hoppers.

~Zahkriiven

**Comment by przemykomo** [comment]
Do you have a more specific idea for better speed control mechanic?

**Comment by Zahkriiven** [comment]
I'd say the easier approach in my opinion could be to use the sprint key to toggle between full throttle mode and low throttle mode.
Other but more complex approach could be something like sprint + mouse wheel to regulate throttle.

Also i'm not too keen on the fact that the plane slowly tilts down (or up with dragon upgrade) and have to keep it straight.
