### ISSUE TITLE
Not an issue but a Suggestion: weaponry of a sort

### ISSUE THREAD

**Issue by hagfelsh** [przemykomo/simple-planes#37]
Some ideas that sound fun:

- drop TNT like bombs

- spray harming potion to damage enemies but not the pilot (so far i've killed myself every time I've done this)

- Maybe even make explosive arrows or a rocket-enabled gunpowder charge for the shooter for a faster rate of explosive hits (maybe non griefing too, or perhaps just scorch the hit block, etc)

**Comment by adoxentor** [comment]
Thanks for the suggestion, I am always happy to get some.
big planes can drop TNT (try TNT one hand flint&steel in the second).
sprayer can spray potions.
I was thinking of adding more fire charge like weapons, but it just felt useless in my testing. 
some more advenced weapons might come in the future.
