### ISSUE TITLE
todo and plans

### ISSUE THREAD

**Issue by adoxentor** [przemykomo/simple-planes#4]
Hope i'm not over stepping...
I wasn't originally planning on adding more than easy flight, but i'm having fun so in order to continue I think we should communicate our goals.
My ideas are:

- side chest upgrade(like donkey's), and big crate upgrade for back seat.
- custom inventory window like in horses. [see this](https://github.com/andrew0030/Pandoras-Creatures/blob/e82d731d2eee1372b1cfc5f7a2ea92e7384c338d/src/main/java/andrews/pandoras_creatures/entities/BufflonEntity.java#L1108)
- folding upgrade, makes the plane return to players inventory upon departure. (kinda late game probably - ?enchantment?)
- keeping everything **simple**.
- ability to remove mobs from the plane [like this](https://www.curseforge.com/minecraft/mc-mods/get-out-of-my-boat)
- plane crash, while I like the idea, it is hard to think what parameters should be, maybe look at the elytra's code.

code staff
- unifying the woods into a field in the plane
- moving the furnace to upgrades to make it a space believe for future engines, or available seat in external engine like solar. 
- ?texture baking? adding support for modded woods/ other materials, maybe even build it in reload time and allowing datapacks. easiest way will be taking [example from this](https://github.com/Markus1002/Extra-Boats/blob/1a7cf32938c46c3380d09e6a345de27a6323d5d5/src/main/java/com/markus1002/extraboats/common/entity/item/boat/ModBoatEntity.java#L28) 
- ??maybe add realistic flight physics, if someone is extremely bored.

Because of the times i don't have much to do, so again sorry for going all in on your project,
all the best adox.
p.s. If you invite me to go all in, we might need a better communication channel, but in any case this is a good place to document plans and goals.

**Comment by przemykomo** [comment]
- I'm planning to add chest upgrade like the TNT upgrade.
- Furnace as an upgrade was also my idea I'm going to do that after finishing current upgrades.

And about modded woods:
 haven't find any information about runtime texture baking for entities. I was using hardcoded enum before and it isn't great idea. Future modded woods are actually main reason why I changed to inhertance. Maybe we could write custom EntityType which would have a field with the planks registry name (for example oak furnace plane would have "minecraft:oak_planks")? I'm open for ideas, but I'm sure going back to hardcoded enum is bad idea.

You can add me on discord if you want a better communication channel: Przemek#7245
