### ISSUE TITLE
Non-oak helicopter recipes don't exist in-game.

### ISSUE THREAD

**Issue by SiliconEnt** [przemykomo/simple-planes#41]
Minecraft 1.16.4
Fabric Loader 0.10.8
Fabric API 0.28.1
Simple Planes 3.2.3 (Fabric)

Spruce, birch, jungle, acacia, dark oak, crimson, and warped helicopter recipes don't exist in-game. They aren't functional in crafting tables and don't appear in REI. All other vanilla-wood vehicle recipes — including the oak helicopter — work fine. I haven't tested with Forge.

I don't think I need to post a log as I've traced the issue: these 7 helicopters are the only vanilla-wood vehicles in the mod whose recipe jsons have matching mcmeta files. These mcmetas check against the names of the wood types as if they were mods that could be loaded. E.g. checking for "spruce" as the name of a mod. As these woods are part of Minecraft, not their own mods, the recipes never become active.

To make sure, I created a datapack that replaces every vanilla wood name in those 7 mcmeta files with the word "minecraft" and the broken recipes became functional.

Suggested fix: remove the recipe mcmeta files for vanilla-wood Helicopters to match your handling of vanilla-wood Planes.

Thanks for your time!

**Comment by przemykomo** [comment]
Closed because recipes won't be in workbench after mod rewrite (which will be the next version).
