### ISSUE TITLE
[1.16.4] Fishing the plane launches it in air

### ISSUE THREAD

**Issue by tanyan-tanyan** [przemykomo/simple-planes#42]
Demonstration: [https://www.youtube.com/watch?v=SOy0uXfkvBA](url)

I'm both amazed and terrified of how easy it was to launch it with just the fishing rod...

**Comment by przemykomo** [comment]
I might try to fix it, but at the same time I want to keep it, because it's just hilarious (just like fishing the player can launch them like 20 blocks up).
