### ISSUE TITLE
[1.16.4] Items tagged 'simpleplanes:not_fuel' still get eaten up by the plane

### ISSUE THREAD

**Issue by tanyan-tanyan** [przemykomo/simple-planes#43]
I just lost my god tier bow while riding in a friend's large plane because I right clicked it in plane while trying to shoot something, despite the fact that the bow had a tag 'simpleplane:not_fuel'. This also happens with fishing rods.

**Comment by DarkScorn** [comment]
I have the same problem, crossbow also vanishes.

**Comment by przemykomo** [comment]
Closed because after rewrite the furnace engine will have an inventory with a fuel slot so the not_fuel tag won't be needed.
