### ISSUE TITLE
i can't move foward 1.12.2

### ISSUE THREAD

**Issue by a7lm** [przemykomo/simple-planes#44]
in the 1.12.2 version I can't move foward or up with a plane/large plane/cargo plane, but with an helicopter I can move correctly.
One of my friends joined to my world and he can move the planes.
please fix this bug is too annoying

**Comment by NightScale5755** [comment]
Remove BetterFPS. It conflicts with the 1.12.2 version. That should fix the issue

**Comment by a7lm** [comment]
I haven't got better FPS on my modpack

**Comment by NightScale5755** [comment]
well uhhh.. I know with just SimplePlanes installed, this issue does not exist. 
Also, a modlist would help?

**Comment by a7lm** [comment]
Biomes o'plenty
Chameleon (storage drawers library)
Croparia
Dynamic trees (and dynamic trees BOP)
Elevator mod
Extra ultils 2
Gaia dimension
Hwaila
Jei
Journeymap
Redstone paste
Simple planes (obviously)
Storage drawers 
Coral tombstone

**Comment by NightScale5755** [comment]
Hmmm.. I don't use almost any of those... Maybe someone else can help out?

**Comment by a7lm** [comment]
You can try to find and incompatibility with any of these mods?

**Comment by tanyan-tanyan** [comment]
Did you check your keybinds?

**Comment by a7lm** [comment]
That's not the problem

**Comment by voroxgoodman** [comment]
The item to put the fuel is missing in 1.12.2

**Comment by sumezawa** [comment]
I also have this same issue in 1.12.2,
w does not move forward the plane (it just use up fuel)
