### ISSUE TITLE
Registries Not Found

### ISSUE THREAD

**Issue by R0B0T-dev** [przemykomo/simple-planes#45]
![image](https://user-images.githubusercontent.com/65292296/104367451-bd61af00-5512-11eb-9792-1c12c18ffeb6.png)

![image](https://user-images.githubusercontent.com/65292296/104367506-d5393300-5512-11eb-8650-45004c107497.png)

1.12.2 Server

I'm able to craft the plane but I am not able to place it on the ground.

**Comment by przemykomo** [comment]
It looks like the server had the simple planes mod removed. Check if the mod is installed.
If it's actually somehow a bug in a mod itself, it will be fixed after rewrite.

**Comment by R0B0T-dev** [comment]
> It looks like the server had the simple planes mod removed. Check if the mod is installed.
> If it's actually somehow a bug in a mod itself, it will be fixed after rewrite.

Okay.

**Comment by R0B0T-dev** [comment]
This is the actual error code after trying to place the plane or helicopter down.
![image](https://user-images.githubusercontent.com/65292296/104439673-474c5f00-5589-11eb-9954-dc7a00cbcadd.png)

**Comment by R0B0T-dev** [comment]
I have also deleted the full config file inside the server as also the jar and reinstalled it there as also on my client side too.

**Comment by przemykomo** [comment]
I see, it will be fixed after rewrite.
