### ISSUE TITLE
Crash when flying over an ocean

### ISSUE THREAD

**Issue by bendooms** [przemykomo/simple-planes#46]
My server is having this problem where the server crashes when a player flies over an ocean with a plane/helicopter. Here's the crashlog:
[crash-2021-01-24_23.54.21-server.txt](https://github.com/przemykomo/simple-planes/files/5864954/crash-2021-01-24_23.54.21-server.txt)

**Comment by przemykomo** [comment]
This is either a vanilla bug or some mod modifies dolphin behaviors. Nothing related to simple planes.

**Comment by bendooms** [comment]
Thank you! I'm guessing it is an incompatibility with Lithium. I just read up about that mod and it appears to mess around with Tick Times. I'll go ahead and remove that
