### ISSUE TITLE
(1.16.5) crashing on server on version 4.0.2

### ISSUE THREAD

**Issue by sirben99** [przemykomo/simple-planes#51]
Hey!

I got crash on server with the latest beta version of the mod (4.0.2)

Forge version: Latest 1.16.5
Mod version: Latest Beta version (4.0.2)

Crash log attachted to the issue
[crash-reports_crash-2021-02-08_19.25.35-fml.txt](https://github.com/przemykomo/simple-planes/files/5945921/crash-reports_crash-2021-02-08_19.25.35-fml.txt)

**Comment by przemykomo** [comment]
Should be fixed in the next version.
