### ISSUE TITLE
I can't use this mod on a server.

### ISSUE THREAD

**Issue by bananapizzuh** [przemykomo/simple-planes#53]
the errors:
Mod File: simpleplanes-1.16.4-4.0.2.jar
	Failure message: Simple Planes has class loading errors
		java.lang.NoClassDefFoundError: net/minecraft/client/renderer/entity/model/EntityModel
	Mod Version: 1.16.4-4.0.2
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.ClassNotFoundException: net.minecraft.client.renderer.entity.model.EntityModel

**Comment by przemykomo** [comment]
update, 4.0.3 doesn't have this problem
