### ISSUE TITLE
Crash on shift click

### ISSUE THREAD

**Issue by ShadowCube264** [przemykomo/simple-planes#54]
In the latest version of the mod, the game crashed when I tried to use shift-click to take a crafted plane out of the plane workbench. I was on Minecraft 1.16.5, with forge version 36.0.1.

[crash-2021-02-16_12.22.13-client.txt](https://github.com/przemykomo/simple-planes/files/5988524/crash-2021-02-16_12.22.13-client.txt)

**Comment by przemykomo** [comment]
Fixed in 4.0.4 version
