### ISSUE TITLE
[Suggestion] Compatibility for dropping modded explosives

### ISSUE THREAD

**Issue by AbacusOperator** [przemykomo/simple-planes#55]
It would be nice if it would be possible to place inside the plane and drop the following modded explosives:

- **Thermal Series**
- - PNT (thermal:phyto_tnt)
- - Inferno Explosive (thermal:fire_tnt)
- - Tectonic Explosive (thermal:earth_tnt)
- - Glacial Explosive (thermal:ice_tnt)
- - Fulminating Explosive (thermal:lightning_tnt)
- **Mekanism Additions**
- - Obsidian TNT (mekanismadditions)
- **Ballistix**
- - Obsidian Explosive (ballistix:obsidian)
- - Condensive Explosive (ballistix:condensive)
- - Attractive Explosive (ballistix:attractive)
- - Repulsive Explosive (ballistix:repulsive)
- - Incendiary Explosive (ballistix:incendiary)
- - Shrapnel Explosive (ballistix:shrapnel)
- - Debilitation Explosive (ballistix:debilitation)
- - Chemical Explosive (ballistix:chemical)
- - Breaching Explosive (ballistix:breaching)
- - Thermobaric Explosive (ballistix:thermobaric)
- - Contagious Explosive (ballistix:contagious)
- - Fragmentation Explosive (ballistix:fragmentation)
- - Nuclear Explosive (ballistix:nuclear)
- - Antimatter Explosive (ballistix:antimatter)
- - Darkmatter Explosive (ballistix:darkmatter)

**Comment by przemykomo** [comment]
Good idea, but it would take a while to make. Maybe this will be in a different addon mod or something like that

**Comment by przemykomo** [comment]
I made it possible to add custom payload options in 380bff269dc2a866ebefce5227bb3c2218d55cb6
Whenever one of these mods updates to 1.18.2, I'll add compatibility.
