### ISSUE TITLE
Crash on Client with error message on server. Possibly from YUNGs Better Portals

### ISSUE THREAD

**Issue by marewey** [przemykomo/simple-planes#57]
please add mod version + minecraft version + modloader version to every issue, and full server + client log + sceenshot if aplicable.

4.0.6 + 1.16.5 + forge 36.0.26
SERVER:
[latest.log](https://github.com/przemykomo/simple-planes/files/6030432/latest.log)

CLIENT:
[latest.log](https://github.com/przemykomo/simple-planes/files/6030431/latest.log)

CRASH REPORT (CLIENT):
[crash-2021-02-23_04.14.12-client.txt](https://github.com/przemykomo/simple-planes/files/6030436/crash-2021-02-23_04.14.12-client.txt)

**Comment by przemykomo** [comment]
Check out version 4.0.7 on curseforge and let me know if it still crashes.

**Comment by marewey** [comment]
Ok, I got it now, It is alpha but it does work fine now. Thanks!
