### ISSUE TITLE
Server Crash 

### ISSUE THREAD

**Issue by Patrick1417** [przemykomo/simple-planes#6]
Server Crash when right clicking a plane with the new Items, Rocket Booster, Shooter, Sprayer or Floaty Bedding.

Error: java.lang.StackOverflowError

Server Version: Forge 1.15.2
Mod Version: 1.15.2-2.0.1.0.jar

**Comment by przemykomo** [comment]
Could you provide full log?

**Comment by Patrick1417** [comment]
[crash-2020-07-07_01.29.57-server.txt](https://github.com/przemykomo/simple-planes/files/4886005/crash-2020-07-07_01.29.57-server.txt)

There you go :)

**Comment by przemykomo** [comment]
Oh, I probably know what went wrong. It tries to load model which isn't present on server. I'll try to fix it tommorow.

**Comment by przemykomo** [comment]
It should be fixed now, but has not been tested yet.
Check version 2.0.2.0 and write comment here if it works.

**Comment by Patrick1417** [comment]
Thank you for the update, works fine now!!
