### ISSUE TITLE
Can't use while on survival

### ISSUE THREAD

**Issue by heda69** [przemykomo/simple-planes#63]
I run a server for my friends and we wanted to try this mod in it. We are able to craft the planes and helicopters as well as place them on the ground, but when we click to mount them and fly, it doesn't work. It does nothing, we can't elevate the thing, only move it in circles in the same spot (more like spinning it). This only happens when the gamemode is set on survival though, because if I change my gamemode to creative it allows me to actually fly it. 

I've been researching online trying to find a solution for this or find someone that has the same problem-- but to no avail. I've made sure the "allow-flight" option is set to true in the server properties, and even added a few plugins that supposledy fixed the issue with the server not letting players fly (even with the option already set to true), but those don't work either. 

After many attempts and failures with the server, I went solo in an offline world to see if at least it worked there, but there seems to happen the same problem. It lets me fly the planes in creative mode, but not in survival. 

I don't know what else to do, or what could be the cause of this issue, as I'm not that good with programming and java and such. Also, when running the server and trying to fly them in survival, it doesn't give me any kind of error-- neither in-game nor in the actual server console, so I don't really have any log file or something of the sort to include here. I'm currently doing all of this in the Minecraft version 1.16.4, with Forge version 1.16.4-forge-35.1.37, and finally Simple Planes version -1.16.4-4.1.2.

I'm truly sorry if this comes off as bothering or troublesome but honestly I'm completely lost in this matter and, as I said previously, I haven't seen anyone else with this kind of problem. If someone knows what's going on, how to fix it or simply need me to send something else, just let me know. Thank you in advance.

**Comment by przemykomo** [comment]
Right click the plane with a vanilla furnace and then use X to open its inventory, where you put coal.

**Comment by heda69** [comment]
oh my god I can't believe it was that simple. Okay I feel stupid now hahhah, thank you very much for telling me.
