### ISSUE TITLE
I cant charge the plane for some reason

### ISSUE THREAD

**Issue by gamerrrrrboy** [przemykomo/simple-planes#69]
I have it set up where the plane is on two chargers but its not charging

**Comment by przemykomo** [comment]
You need to connect some Forge Energy source from other mod.

**Comment by ppman888** [comment]
yo bro can you link the mod please

**Comment by Weedoof** [comment]
No. Find one yourself. Basically any tech mod works fine.

**Comment by ppman888** [comment]
ok thanks
