### ISSUE TITLE
Keybinding Issue

### ISSUE THREAD

**Issue by Foozey** [przemykomo/simple-planes#71]
If a keybinding to access the plane engine is the same as another keybind, one of the keybinds won't work at all. For example, if you have inventory set to [E] and access plane engine set to [E], either the inventory or plane engine won't work at all. This is annoying as sometimes you want to have the same keybind as something else.

**Comment by przemykomo** [comment]
Yes that's how keybinds in minecraft work.

**Comment by Foozey** [comment]
No, other keybindings that are the same don't work like that. For example, in your own mod, you have [Space] for boost, but also [Space] for jump, yet they both still work. It's just that specific keybinding. If you ride a horse in Minecraft, you can press [E] to open the inventory, yet you can also press [E] to open the normal inventory if you're not on the horse. This is how I'm trying to make it work with your mod because it matches vanilla the best. Pressing [E] should be able to open the plane inventory while you're in the plane, but opens the normal inventory if you're out of the plane.

**Comment by przemykomo** [comment]
Pressing [E] opens the inventory if the plane has chest. Notice that the horse doesn't have a different keybind for inventory, it uses the default one, just as the plane with chest does.

**Comment by Foozey** [comment]
Ah, sorry, you're right. That slipped my mind. Thank you for clarifying.
