### ISSUE TITLE
Using a projectile weapon whilst inside the aircraft destroys it, sometimes even if shooting through a window.

### ISSUE THREAD

**Issue by Kaleidio** [przemykomo/simple-planes#77]
Clarification; the player using weapons whilst inside the aircraft, not the aircraft's cannons

I assume this is because you have the hitbox to be larger than the player, making it impossible to shoot whilst inside the aircraft.  I'm using mr.crayfish's guns mod and it would have been awesome to hold a minigun whilst flying a helicopter, but as it stands now it's impossible as the first shot I take, nine times out of ten, destroys the helicopter instantly.

Can you add some sort of special case statement that doesn't accept damage from player weapons or projectiles, specifically of the player uuid who is riding the craft?

**Comment by przemykomo** [comment]
Sure, I'll look into that.

**Comment by noddynod443** [comment]
I have the same issue, would love to be able to shoot mr crayfish guns or any other projectile weapon from the aircraft...safely

**Comment by Kaleidio** [comment]
please backport this change to 1.16.5
