### ISSUE TITLE
[Feature Request] Seat belts

### ISSUE THREAD

**Issue by AngleWyrm10** [przemykomo/simple-planes#78]
I just used a helicopter to fly over rough terrain to a desert to get me some cactus. Great version of flight, thanks! 

I fell out several times. Lucky I have bouncy boots to protect me, but as I watched my unmanned chopper sail off into the distance I really wished I hadn't accidentally pressed the dismount button.

Would a seat belt be a fun thing to add/make?

**Comment by przemykomo** [comment]
What do you mean by seat belts? You exit the aircraft after trying to crouch, just like in boats, so... just don't crouch and then you won't fall out, I guess?

**Comment by AngleWyrm10** [comment]
Yes, that is both correct and also did not happen that way.

What I mean by seat belt would be a new invention for Minecraft, something that has not been done before. A method of preventing accidental dismount from pressing a button that also serves as the down button when swimming.

Maybe it is an item that when placed on the hotbar prevents dismounting.

**Comment by przemykomo** [comment]
This would be a separate mod as it wouldn't be plane-specific. If there would be something to change in simple planes in order for it to work, I'll be happy to do that.

**Comment by Weedoof** [comment]
This mau not be  exactly what you're looking for but I do think it's worth mentioning - there are a few mods that let you separate the crouch and dismount keybindings. Quark is one, if memory serves, but there are other standalone mods that should work just as well.
