### ISSUE TITLE
Suggestion:zeppelins inventory etc

### ISSUE THREAD

**Issue by Wotzinator** [przemykomo/simple-planes#8]
first of all i have to say i love this mod please keep up the good work
i hope my suggestions are good enough to make it into this mod
 an upgrade inventory for the planes would be good so you can keep track of them easily
 id also like to see a fluid based engine wich you can config to take other modded fluids(for example diesel from immersive engineering)
also it would be kinda nice too have the ability too drive the planes on the ground to reorient them

also i think a zeppelin would be cool it would move slower but could be used to haul  a gigantiv amount of items

**Comment by przemykomo** [comment]
What do you mean by `an upgrade inventory for the planes would be good so you can keep track of them easily`?
Other engines, like the fluid based one, are going to be added in the future.
Zeppelin is great idea, but it would be different mod.

**Comment by Wotzinator** [comment]
i just find the fact that you need to right click the plane with the upgrades and fuel somewhat tedious

**Comment by przemykomo** [comment]
Why and what would be better?

**Comment by przemykomo** [comment]
Closed due to inactivity.
