### ISSUE TITLE
Suggestion: Falling Planes, plane durability and other things.

### ISSUE THREAD

**Issue by Matthi3000S** [przemykomo/simple-planes#84]
1. When a plane is destroyed in the air, it won't be dropped instantly. Instead, the plane will enter a state in which the engine stops and smoke comes out of it. The plane is still able to be steered and it slowly falls down. If it meets ground, the plane explodes and becomes an item with mild damage to the engine, but if the plane hits water, it's not destroyed, but the engine is slightly damaged and the plane falls down to the bottom of the sea until it hits the bottom and becomes an item. If the plane hits water and has floaty bedding, the plane will become an item and the engine will have no damage.
2. Different types of planes with different durability and speed. There are x amount of tiers of durability: wood, stone, iron, gold, diamond and netherite.
The lower the tier, the higher the speed and the lower the durability. Gold and netherite are exceptions to the speed part, as gold is as durable as iron, but as fast as wood and netherite is more durable than diamond and as fast as iron. Wood is the base tier and keeps the current durability of planes, and durability goes up. Some people have also complained about the durability of planes, as they use [Mr. Crayfish's Gun Mod](https://www.curseforge.com/minecraft/mc-mods/mrcrayfishs-gun-mod) with this mod.
3. Parachutes. Just that. Maybe parachutes could be attached to planes and wouldn't take up space on the inventory f the player, but that's not necessary. They could also be destroyed.
4. (Not very likely) Anti-Air Guns. They would be pretty big and as vanilla plus-ey as possible. It would use arrows, fire charges (for wood planes), TNT and fireworks. They would have a slight aim assist to help as this wouldn't be easy to use. Maybe it could even have a special ammunition that would be incredibly powerful

**Comment by przemykomo** [comment]
Good ideas. I'll definitely implement something similar.
