### ISSUE TITLE
simpleplanes.refmap.json could not be read

### ISSUE THREAD

**Issue by evg-zhabotinsky** [przemykomo/simple-planes#88]
```
[main/WARN] [mixin/]: Reference map 'simpleplanes.refmap.json' for simpleplanes.mixins.json could not be read. If this is a development environment you can ignore this message
```
This is *not* a development environment. Should I ignore it anyway?
MC 1.18.1, Forge 39.0.66, SimplePlanes 4.8.1

**Comment by przemykomo** [comment]
If it doesn't crash you can ignore it. I removed mixin in the next version anyway.
